%% --------- CASO PRUEBA 2 ------------------
% a,b= parametros de ecuacion de la recta
% y  = puntos en R^{3 x n} donde se ubican las rocas de kriptonita
% C  = cota del valor de aturdimiento 
%
close all  %cierra todas las ventanas
clear variables  %elimina variables del entorno

%% CASO 1
%
% Definiciones 

%parametros de la recta
a = [1;2;3];
b = [1;1;1];

% coordenadas de las naves estelares
y=[       0.8          1.1          0.9;...
            1          0.6            1;...
          1.5          2.1          0.7;...
          2.3          2.1          1.5;...
          0.9          1.3          2.2;...
          1.5            2          2.2;...
          1.1          2.4          2.6;...
          1.6          1.9          2.5;...
          2.5          2.4          2.3;...
          2.9          2.5          2.9;...
          1.3          1.8          2.1;...
          1.5          1.9          3.4;...
          1.6          3.4            4;...
          1.9          2.5            4;...
          1.3            3          3.2;...
          1.6          2.4          4.1;...
          1.8          3.2          3.8]';

% cota para el nivel de aturdimiento
C=23;


% Grafico de la funcion de aturdimiento

graficador(y,a,b)


